services:
  nuxt:
    container_name: project-generator-wizard-web-app
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    command: /bin/sh -c "npm install && npm run dev"