<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;
use Tests\Traits\ApiSignIn;

class LogoutTest extends TestCase
{
    use ApiSignIn;

    private string $logOutRequestUrl;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logOutRequestUrl = route('logout');

    }

    /**
     * A basic feature test example.
     */
    public function test_user_without_token_can_not_logout(): void
    {

        $response = $this->postJson(
            $this->logOutRequestUrl
        );

        $response->assertUnauthorized();
    }

    public function test_user_can_logout(): void
    {
        $user = $this->signIn();

        $response = $this->postJson(
            $this->logOutRequestUrl
        );

        $response->assertOk();

    }
}
