<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use Tests\Traits\ApiSignIn;

class UserShowTest extends TestCase
{

    use ApiSignIn;
    private string $showUserUrl;

    private User $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();

        $this->showUserUrl = route('users.show', ['user' => $this->user->id]);
    }

    public function test_unauthenticated_user_gets_401()
    {

        $request = $this->getJson(
            $this->showUserUrl,
        );

        $request->assertUnauthorized();

    }

    public function test_cant_update_non_existent_user(): void
    {

        $this->signIn();

        $nonExistingUserUrl = route('users.show', ['user' => 10000]);

        $request = $this->getJson($nonExistingUserUrl);

        $request->assertNotFound();
    }

    public function test_user_can_be_shown(): void{

        $this->signIn();

        $request = $this->getJson($this->showUserUrl);

        $user = $request->json()['data']['user'];

        $request->assertJsonStructure([
            'data'=>[
                'user'
            ]
        ]);


        $request->assertJson([
            'data'=>[
                'user'=>$user
            ]
        ]);


    }

}
