###############################################################################
#                          Generated on docker.io                          #
###############################################################################
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: 'postgres:15-alpine'
    working_dir: /src
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '7604:5432'
    volumes:
      - {{databaseVolumeName}}:/var/lib/postgresql/data

  db_test:
    container_name: ${DB_TEST_CONTAINER_NAME}
    image: 'postgres:15-alpine'
    working_dir: /src
    environment:
      - POSTGRES_USER=${DB_TEST_USER}
      - POSTGRES_PASSWORD=${DB_TEST_USER}
      - POSTGRES_DB=${DB_TEST_NAME}
    ports:
      - '7603:5432'
    volumes:
      - {{databaseTestVolumeName}}:/var/lib/postgresql/data

  webserver:
    container_name: ${WEBSERVER_CONTAINER_NAME}
    image: 'nginx:alpine'
    working_dir: /src
    volumes:
      - './src:/src'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'

  php-fpm:
    container_name: ${PHP_CONTAINER_NAME}
    build: docker/php-fpm
    working_dir: /src
    volumes:
      - './src:/src'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
volumes:
    {{databaseVolumeName}}:
      driver: local
    {{databaseTestVolumeName}}:
      driver: local